# Deploy OpenReply to VPS via SSH.
# Usage: .\infra\deploy-vps.ps1

$ErrorActionPreference = "Stop"

$VpsHost = if ($env:VPS_SSH_HOST) { $env:VPS_SSH_HOST } else { "vps" }
$RemoteDir = if ($env:VPS_REMOTE_DIR) { $env:VPS_REMOTE_DIR } else { "/opt/openreply" }
$PublicUrl = if ($env:OPENREPLY_PUBLIC_URL) { $env:OPENREPLY_PUBLIC_URL } else { "http://130.185.76.124:3200" }
$PostgresPassword = if ($env:POSTGRES_PASSWORD) { $env:POSTGRES_PASSWORD } else { -join ((48..57) + (65..90) + (97..122) | Get-Random -Count 32 | ForEach-Object { [char]$_ }) }

$RepoRoot = Split-Path $PSScriptRoot -Parent
$LocalEnv = Join-Path $RepoRoot ".env"
$VpsEnv = Join-Path $PSScriptRoot ".env.vps"

if (-not (Test-Path $LocalEnv)) {
  throw "Missing $LocalEnv. Configure local OpenReply first."
}

Write-Host "==> Testing SSH to $VpsHost..."
ssh -o BatchMode=yes -o ConnectTimeout=15 $VpsHost "echo ok; docker compose version" | Out-Host
if ($LASTEXITCODE -ne 0) {
  throw "SSH to '$VpsHost' failed. Check ~/.ssh/config and your PEM key."
}

Write-Host "==> Building VPS env file..."
$out = @()
$out += "# Generated by deploy-vps.ps1"
$out += "NEXTAUTH_URL=$PublicUrl"
$out += "POSTGRES_PASSWORD=$PostgresPassword"
$out += "OPENREPLY_PORT=3200"
foreach ($line in Get-Content $LocalEnv) {
  if ($line -match '^(NEXTAUTH_URL|DATABASE_URL|REDIS_URL|POSTGRES_PASSWORD|OPENREPLY_PORT)=') { continue }
  $out += $line
}
$out | Set-Content -Encoding utf8 $VpsEnv

Write-Host "==> Syncing repo to ${VpsHost}:${RemoteDir}..."
ssh $VpsHost "mkdir -p $RemoteDir"
$tarPath = Join-Path $env:TEMP "openreply-deploy.tgz"
Push-Location $RepoRoot
try {
  tar -czf $tarPath --exclude=node_modules --exclude=.next --exclude=.git --exclude=infra/.env.vps .
} finally {
  Pop-Location
}
scp $tarPath "${VpsHost}:/tmp/openreply-deploy.tgz"
scp $VpsEnv "${VpsHost}:${RemoteDir}/.env"

$remoteCmd = "cd $RemoteDir && tar -xzf /tmp/openreply-deploy.tgz && rm /tmp/openreply-deploy.tgz && export POSTGRES_PASSWORD='$PostgresPassword' && docker compose -f infra/docker-compose.vps.yml up -d --build && docker compose -f infra/docker-compose.vps.yml ps && curl -sf http://localhost:3000/api/health"
ssh $VpsHost $remoteCmd

Write-Host ""
Write-Host "Deployed. Public URL: $PublicUrl"
Write-Host "Health: ${PublicUrl}/api/health"
